version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      
  server:
    build: .
    env_file:
      - .env
    ports:
      - "4444:4444"
    volumes:
      - .:/usr/src/beeus-api
    command: air ./src/main.go
    
volumes:
  postgres-db:
    