version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=beeus
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  server:
    build: .
    env_file:
      - .env
    ports:
      - "4444:4444"
    volumes:
      - .:/usr/src/beeus-api
    command: air ./src/cmd/main.go

volumes:
  postgres-db:
